README.md

Low
Needed to update the README to account for our hot new branding
NA
#12 
NA
NA
NA
NA
@davidpellerin

[FIX] - Fixes #12, quick start

---

src/index.js
src/middleware/json-api/req-get.js

I have it patched locally, but would like it patched upstream before using this anywhere else.
- index.js - added GET middleware reference
- req-get.js - created GET middleware

Fix compatibility with fortune-json-api

---

src/index.js

URI encode the ids for creating paths/URLs

---

src/middleware/json-api/req-delete.js
src/middleware/json-api/req-get.js
test/api/api-test.js

send truly empty bodies in GET and DELETE requests

---

README.md

This change adds a Snyk badge which displays the status of whether or not the application contains any known vulnerabilities.

adding Snyk

---

package.json

https://github.com/npm/npm/issues/4040#issuecomment-27159695
It is not working under window -> Yes, blocking me ...
Please don't include `./node_modules/.bin/` in the `package.json` 
https://github.com/npm/npm/issues/4040#issuecomment-27159695
some `npm` not working under window
try `npm build` then `npm test`
Is this needed?
https://github.com/npm/npm/issues/4040#issuecomment-27159695

Now also runs under windows

---

src/index.js

NO
missing template string quotes to print out modelName

fix error log

---

README.md

Highlights the beauty of devour's design. :-)
None
Documentation

A note on making cancellable requests

---

src/middleware/json-api/res-errors.js

Support response errors with no data. Return status text instead

---

src/index.js

Explain what changed and why.
Link to any relevant task(s) or ticket(s) in the bug tracker.
Link to any existing documentation that could make the change easier to understand for the reviewer.
Mark any areas that are work in progress or require follow up.
Note anything that is waiting on other departments or team members.
Call out any legal, security, or privacy concerns.
If any third-party dependencies have been added, explain what they are and why you chose them.
Mention people who would be interested in the changeset:
Engineer(s) who wrote the old version
Designer(s)
Product manager (if they’re interested)

Print available models on missing models' API resource definition

---

src/middleware/json-api/_deserialize.js

HIGH
pass included params to custom deserializer

pass included params to custom deserializer

---

src/index.js
src/middleware/json-api/_deserialize.js

Added some console asserts to test required arguments for the destroy() function
Also some variable renaming for readability

Add asserts for arguments of destroy()

---

src/index.js

I am not sure this is really a must, but this is how it was defined
earlier, and I want to avoid regressions.
Explain what changed and why.
Link to any relevant task(s) or ticket(s) in the bug tracker.
Link to any existing documentation that could make the change easier to understand for the reviewer.
Mark any areas that are work in progress or require follow up.
Note anything that is waiting on other departments or team members.
Call out any legal, security, or privacy concerns.
If any third-party dependencies have been added, explain what they are and why you chose them.
Mention people who would be interested in the …

Empty data and meta fields should be empty object, not undefined

---

README.md

By the way `--save` is not necessary now, it's by default.
No.
Not needed.
Explain what changed and why.
Better understand of the doc IMO.

docs(README): split installation part

---

package-lock.json
package.json

Upgrade axios dependency to avoid potential DoS issue.
See https://nvd.nist.gov/vuln/detail/CVE-2019-10742

DoS fix - Upgrades axios to 0.18.1

---

src/middleware/json-api/_serialize.js
test/api/serialize-test.js

Is this PR blocking your next action? yes
Explain what changed and why.
Using an arbitrary request using the request method does not work and throws an error as it doesn't take a model name, and it calls the serializer which expects a model name. 
Link to any relevant task(s) or ticket(s) in the bug tracker.
Link to any existing documentation that could make the change easier to understand for the reviewer.
Quick start section
// To make arbitrary requests through the middleware stack
jsonApi.request('https://example.com', 'GET', { a_query_param: 3 }, { some_payload_item: 'blah' })
Mark any areas that are work in progress or require follow up.
Note anything that …

fixes not found model error for request method

---

package-lock.json
package.json

Change the dependency on Axios from 0.19.0 to 0.21.0. The newer version has some fixes that people might want to have and this will remove the need for them to keep two versions installed in their project.

Update Axios dependency to the latest version

---

README.md
package.json

I updated all GitHub URLs to to the new repo location.

Update all GitHub URLs

---

package-lock.json

I ran `npm update babel...` for all babel-packages.
https://github.com/advisories/GHSA-67hx-6x53-jw92

Upgrade babel to address vulnerability

---

.github/workflows/node.js.yml

Set up a new GitHub Action to run tests for us. I would like to run this on each pull request.

Create a CI workflow
