middleware/json-api/rails-params-serializer.js
Medium. Prevents the construction of queries with more complicated/structured query params.
Disabled qs URI encoding.
Before:
`api.find('match-result', '123', {filter: {status: 'fuzzy'}})` 
results in: `/api/match-results/123?filter%5Bstatus%5D=fuzzy`
After:
`api.find('match-result', '123', {filter: {status: 'fuzzy'}})`
results in `/api/match-results/123?filter[status]=fuzzy`
=> disabled qs encoding

package.json, test/mocha.opts
This pull request moves the mocha cli switches into `test/mocha.opts`, a standard location mocha looks for, and out of `package.json`'s test script definition. This allows us to run `mocha` from the command line with our own switches for more expressive testing, and DRYs up our `package.json`.
=> Moved mocha options to test/mocha.opts

README.md, index.js, test/api/api-test.js, test/api/deserialize-test.js, test/api/serialize-test.js, test/mocha.opts
This pull request addresses issue #5 by removing the singleton pattern in favour of creating instances with the `new` keyword, and using the ES6 `constructor` function on the `JsonApi` class.
=> Removed singleton pattern

middleware/json-api/_deserialize.js, middleware/json-api/res-deserialize.js
Low. This PR simply provides a more helpful error message when there is a misalignment defined amongst models.
Previously when the JSON API type attribute didn't match the specified Devour model the error message did not provide much indication as to where the problem lay. It read: `TypeError: Cannot read property 'attributes' of undefined`.
Now, when the Devour model and JSON API type attribute do not align, Devour displays a more helpful error message that reads: `The JSON API response had a type of "match-result" but Devour expected the type to be "match-set".`.
=> improved error message when models do not match

.gitignore, index.js, package.json, test/api/api-test.js, test/api/deserialize-test.js, test/api/serialize-test.js
No
Initializer now takes an object instead of list of arguments, this allows better extendability. See issue #15 
`npm test`
See #15
See README.MD
https://github.com/twg/devour/blob/feature/hash-initializers/test/api/api-test.js#L22-L32 ES6 + Babel is not passing this test for some reason
Also, general consensus on using lodash as an utility package?
N/A
N/A
@Emerson @derek-watson
=> Converted the initializer to object initializer

.gitignore, README.md, package.json
I've added a series of npm scripts to `package.json`, most importantly a prepublish step that runs our source through Babel.
NPM scripts:
* prepublish
* publish
* release:patch
* release:minor
* release:major
* compile
* watch
* test
=> Added NPM prepublish

src/middleware/json-api/res-deserialize.js
Medium
The response object can contain a `links` property, however, this property was not available on the collection after running through Devour's deserializer (the `meta` property was being carried over correctly though).
=> added links to response object

README.md, src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
Currently blocked using this library as parsing of resources skips meta and links members. We also have some funky deserialization requirements that require the ability to specify a custom deserializer for a resource.
1. **Resource deserialization will now include resource level meta and links objects.**
The specification indicates that the top level document may contain an 'included' member which is an array of resource objects. Resource objects are further defined to allow inclusion of meta and links information. References linked in the Documentation section of this PR.
2. **Resource definition via jsonApi.define now accepts a deserializer option for custom deserialization**
This is added to support some custom deserialization needs for client work, and it adds parity with the …
=> Improve deserialization

src/middleware/json-api/_serialize.js, test/api/serialize-test.js
Merging sooner rather than later would be ideal (pending discussion/approval, obviously), as this is relied on in production.
Alters the behaviour around serializing unspecified/null/empty relationships as per the description in #29 - the tests included in this PR describe the changes in detail, but the summary is:
- unspecified relationships are not serialized
- hasOne relationships that are deliberately set to null are serialized correctly
- hasMany relationships that are deliberately set to empty arrays are serialized correctly
- relationship object is omitted if no relationships are specified at all
=> Serializer handles null/unspecified relationships

README.md, package.json, src/index.js, test/api/api-test.js
The rationale behind this is that pagination links (and other linked resources) are something that is fairly commonplace, however devour does not currently implement any feature that allows consumers to follow those links, which requires (for example) manual management of pagination parameters and construction of related resource URLs using the builder.
This PR introduces `request`—a very thin wrapper around `runMiddleware`, primarily to have something documented that allows arbitrary requests to be made through the middleware stack.
This might require a bit of discussion as it omits the model part of the request that would normally be present on requests. I'm not sure what side effects this might have, but in my in-app testing it hasn't caused any notable issues.
=> Support arbitrary requests

src/middleware/json-api/res-deserialize.js
- fixes #34
The JSON API spec allows for empty responses to successful update requests. This change guards against errors in that case.
=> add guard for valid but empty responses

src/middleware/json-api/req-headers.js
Use lodash's version of `assign` over `Object.assign`.
While this can be polyfilled as mentioned in #40, there's precedent for use of lodash's `assign` already in the project (in [index.js](https://github.com/twg/devour/blob/master/src/index.js#L67)).
Given this is a pretty simple change and doesn't introduce any extra dependencies, I think it's worth doing this to avoid the polyfill requirement in older browsers.
=> Use lodash.assign over Object.assign

package.json, src/middleware/json-api/_deserialize.js
High - this PR is blocking me (though I can link to this specific branch for the time being)
Given the following model:
```
api.define('jobItem', {
haystackSilo: {
jsonApi: 'hasOne',
type: 'silos'
},
needleSilo: {
jsonApi: 'hasOne',
type: 'silos'
}
})
```
Devour ends up overwriting the latter's data with the former. This is because Devour infers the key name based on the format of the attribute object. Specifically, this is defined here: https://github.com/twg/devour/blob/master/src/middleware/json-api/_deserialize.js#L86. `_.findKey` simply returns the *first* key where the attribute object matches. This means regardless of whether Devour is handling the haystackSilo relationship or the needleSilo relationship, the `relationshipName` will always be haystackSilo.
To address this, I simply …
=> pass relationship key explicitly

src/middleware/json-api/res-deserialize.js, test/api/api-test.js
When requesting a single resource and that resource is null i.e. the response is as below
```json
{
"data": null
}
```
then the library would throw an error when attempting to deserialize this null data.
To address this I added a couple of checks that guard against this case.
[Related section in the spec](http://jsonapi.org/format/#document-top-level) (see the description of primary data)
=> Handle null primary data in deserializer

src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
According with the `JSON API` definition, a resource object MAY contain `attributes`.
http://jsonapi.org/format/#document-resource-objects
```
In addition, a resource object MAY contain any of these top-level members:
- attributes: an attributes object representing some of the resource’s data.
- relationships: a relationships object describing relationships between the resource and other JSON API resources.
- links: a links object containing links related to the resource.
- meta: a meta object containing non-standard meta-information about a resource that can not be represented as an attribute or relationship.
```
So, what I did is just checking if `attributes` is defined in the response resource object, before trying to access its properties.
=> fix deserialize resources without attributes

src/middleware/json-api/res-deserialize.js
Our API doesn't include "meta" items for some entities.
JSON API spec mentions that this is optional: http://jsonapi.org/format/#document-meta
Line 35 of _deserialize.js checks if param exists before assigning:
https://github.com/twg/devour/blob/master/src/middleware/json-api/_deserialize.js#L35
This PR just adds the same check to res-deserialize.js.
=> Adding check for params during deserialization

README.md, package.json, src/index.js
High
Devour already provides for the use of a completely custom middleware stack as well as inserting custom middleware, but it doesn't allow outright replacement of a specific piece of middleware. This PR adds `replaceMiddleware`, to do just that.
Readme updated with a simple example.
@Emerson 
@billxinli 
@themarkappleby
=> Simplify individual middleware replacement

src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
Yes, to be able to parse polymorphic relationships and give back the specific type of it
When a `resource` is deserialized, I just added the `type` of the received data in the returned `object`.
The reason is that the `name` of the `attribute` used for the `relationship` in some case (`polymorphic relationship`) does not match with the type of data itself.
Example: http://jsonapi.org/format/#document-resource-object-relationships (look the example they wrote `relationship: author` -> `type: 'people'`)
So to be able to know the specific type of the `relationship` I need to have the `type` of the `attribute` in the `deserialized object`
=> add type property to deserialized resource

README.md, package.json, src/middleware/json-api/_serialize.js, test/api/serialize-test.js
The motivation for this PR is to allow for serializing polymorphic relationships.
A model with a relationship is defined like:
```
jsonApi.define('order', {
name: '',
payables: {
jsonApi: 'hasMany',
type: ????
}
})
```
If `payable` has a polymorphic type, then the type cannot be specified during model definition.
This PR brings in support for serializing types that are not present in model definitions, and can instead be specified directly when a Devour request is being constructed.  See the tests and readme for an example. 
In conjunction with https://github.com/twg/devour/pull/51 this library will have better support in general for polymorphic relationships.
n/a
n/a
@Emerson @billxinli @themarkappleby
=> Allow types to be specified directly for relationships

README.md, package.json, src/index.js, test/api/api-test.js
Added a constructor option in object form to optionally append trailing slashes to either/both collection and resource urls.
Discussed in #57
=> Support in the url builder for trailing slashes.

README.md
The documentation references a `trailingSlashes` option, but the code shows that it's actually called `trailingSlash`. 
This PR updates the language in the README file to reflect that.
=> Fix `trailingSlash` in documentation

README.md, src/index.js, src/middleware/json-api/_deserialize.js, src/middleware/json-api/_serialize.js, src/middleware/json-api/res-deserialize.js, test/api/api-test.js
I have an API which does not pluralize the names of its models. This PR adds an option to disable pluralization so I can use Devour as my client, and also custom pluralization for other users who might have different pluralization requirements not covered by the default `pluralize`.
Incidental to this change is an update to an error message. The original problem was that the error message did not reflect the expected pluralization, leading to the confusing error `The JSON API response had a type of "Products" but Devour expected the type to be "Products"`. While I was at it I also changed the message to reflect the actual underlying problem, modifying the code originally added by #10 as the response model was no longer needed for the error message.
=> Add a config option to disable or change pluralization

README.md, src/index.js, test/api/api-test.js
Yes, we needed to implement this to call some endpoints and reduce numbers of calling
- Added params in the signature of create and update methods.
- Make create or update requests with include params to get back related resources.
=> add params to create and update requests

src/middleware/json-api/_deserialize.js
Yes.
JSON API spec dictates that keys use dashes, but javascript convention is lowerCamel
The examples all use one word keys so the problem of consuming a two-word key never comes up.
This change checks if a lowerCamel attribute exists on the config model if the first does not.
I could have put the replace line before the initial attrConfig assignment but this avoids doing a replace unless the key is missing the first time around.
=> checks if lowerCamel key exists upon missing attr

src/middleware/json-api/res-errors.js
High 
The wrong value was passed to the buildError functions. Therefore the real errors where never returned.
=> buildErrors; pass the correct variable as data is not defined

src/middleware/json-api/rails-params-serializer.js
This looks like the correct encoding now - keys and brackets get left as-is, but any values get encoded.
Keys with spaces in will still be unsupported, but the cause of this bug (and probably the much more common case) of having spaces in the values is fixed by this change.
=> #94 Fixed - Support URL encoding of parameter values

src/index.js, test/api/api-test.js
Priority: low
The absence of this feature can by bypassed by chaining " ->all('relationship')" in the URL builder.
Adds convenient "relationships()" method for URL builder.
https://github.com/twg/devour/issues/46
Example:
```js
const create = this.availableDevices.map((device) => {
return {type: 'devices', id: device.id}
});
JsonApi.one('project', this.project.id).relationships().all('device').post(create)
```
API documentation:
http://jsonapi.org/format/#fetching-relationships
http://jsonapi.org/format/#crud-updating-relationships
=> Add 'relationships()' to URL builder for accessing relationships on API

src/index.js, src/logger.js, src/middleware/json-api/_deserialize.js, src/middleware/json-api/res-errors.js
Priority: high.
It would make testing and debugging much faster and easier.
All the console statements have been removed in favor of the main logger. The logger has been converted to a singleton that can be imported in all files.
Why? Because then logs can be turned off.
See #93.
No documentation changes necessary.
=> Remove console statements and use logger everywhere

package.json, src/index.js, src/middleware/json-api/req-delete.js, test/api/api-test.js
Priority: high
This package fails to comply with the JSON API spec by not allowing relationship records to be deleted at present.
The destroy() method accepts either zero or two arguments. When destroying has-many relationship records, a list of relationship record objects ('type' and 'id') are required. This PR allows for this case.
Related Issue: https://github.com/twg/devour/issues/55
Another PR I submitted which is closely related to this: https://github.com/twg/devour/pull/99
http://jsonapi.org/format/#crud-updating-relationships
A unit test is included, which relies on a hacky work-around of the absence of a "relationships()" chain method for the URL builder, a feature which my other PR linked above addresses. If the other PR is accepted, …
=> Support relationship destroy

package.json, src/index.js, src/middleware/json-api/_deserialize.js, src/middleware/json-api/_serialize.js, test/api/api-test.js
Priority: low
PR as proposed is just a convenience feature for developers and does not affect a production environment.
With the current version (v2.0.3) if the query builder is used to reference a model which is not defined, eventually code execution just fails with no feedback other than an attempt to access an 'options' property on an undefined object. This is a simple change to communicate which model lookup failed.
I included an example unit test however it is currently disabled. IT DOES NOT WORK. Basically I am not familiar with this unit tester and I am not sure how to include an "expect an error to be thrown" test. Please review and adjust, thanks.
=> Model exception handling

src/middleware/json-api/req-delete.js, test/api/api-test.js
Priority: high
Corrects an error in the data package sent with the API request
My PR which added data payload handling to the "destroy()" method does not correctly follow the pattern of the "post()" and "patch()" methods, because it did not take the method input and enclose it within a "data" object as the spec requires. As a result, if used the way intended, the API request would be rejected with a "400 BAD REQUEST" response.
The unit test for this action was also not testing this correctly, hence it got through.
This has been tested in my own project and works as expected.
Example
```js
const payload = [
{type: 'bars', id: '2'},
{type: 'bars', id: '3'}
]
jsonApi.one('foo', 1)->relationships()->all('bar')->destroy(payload)
```
API request to 'http://myapi.com/foos/1/relationships/bars' …
=> Fix destroy data handling

src/index.js
Priority: very high
Yes, this is a fatal error on any API error response including naturally expected responses like 422 on data validation.
This one Logger error message call was missed in the recent conversion to using Logger, which also dropped binding the logger to "this.logger". The current code throws an "undefined" error.
Cause any API error response, either with a bad data package or failing a validation test.
=> Fix Logger error call on API error response

src/middleware/json-api/res-errors.js
medium 
The error handling only supported errors with a pointer. JSON API specs also define errors that have no pointers.  See: http://jsonapi.org/examples/#error-objects-multiple-errors. There are document errors as well as parameter errors. The last one still needs to be added though. 
Also only the title of the error was returned. In our case we also wanted the detail of the error.  That's why I created a object which contains the title and the detail. 
I only tested in our frontend and this works. I did not write new tests. 
It would be nice if we also parse parameter errors correctly.
=> if pointer isn't defined use index as key

src/middleware/json-api/res-errors.js
This PR blocking my next action.
Some operations results in Error object returning from Axios. For example, access denied, network error, etc. All these errors are currently not handled properly by Devour.
https://github.com/twg/devour/issues/130
https://github.com/twg/devour/issues/131
https://github.com/twg/devour/issues/132
=> Handle errors

src/index.js
Blocks integration with Angular (and potentially other code manipulating the global Promise object). Patching the library source code on the consumer side is a possible workaround, but far from ideal.
Previously, devour would always use the es6-promise implementation, even if a global Promise object was available. Preferring the native implementation makes sense already, but in combination with Zone.js, it is necessary not to break functionality. Zone.js augments the global Promise implementation so it correctly interacts with zones - and since devour gets its own Promise implementation, it breaks. The various zone-related interceptors are not called when the promises returned by devour complete, and since Angular triggers its change detection mechanism with these interceptors, that also …
=> Polyfill global Promise

README.md
Low.
I found the documentation around how to write Devour middlewares to be very unhelpful, as with the state my project was in it ended up being a lot of work to get to a point where I could just inspect the payload in a console. Rather than telling people to go find stuff out themselves, the purpose of documentation is to be the place people can look first to find that stuff out.
=> Added some documentation to the README about middleware

src/index.js, src/middleware/json-api/_deserialize.js, src/middleware/json-api/_serialize.js, src/middleware/json-api/req-headers.js, src/middleware/json-api/req-http-basic-auth.js, src/middleware/json-api/res-deserialize.js
PR is not blocking. However, the way devour currently requires lodash makes it impossible to optimise bundles. For example using webpack. Since devour always requires the full library. Devour is the only dependency we have that does this, and the only reason for a couple of hundred unused Kbs in our bundle.js.
Okay....
This PR rewrites the requires to only pick the parts of lodash that are used. Use of lodash `chain` method was removed, and split into a separate call to `last()` and `get`. This makes it easy to optimise bundles that Devour is built into along with lodash.
`npm run test`
=> Require only lodash specifics

src/middleware/json-api/_serialize.js, test/api/serialize-test.js
Unable to use this library given the fact that we need to use meta and links of resources. 
N/A
Currently serialization of resource object only checks for 'type' and 'id' top-level members and everything else is included in 'attributes'. Although these two members are required, specification allows also for 'meta' and 'links' top-level members. With this change, item 'meta' and 'links' fields will be serialized separately as specified in [specification](http://jsonapi.org/format/#document-resource-objects)
Tests have been added to test/api/serialize-test.js to cover for default serialization of meta and links members on resources.
Related to [this issue](https://github.com/twg/devour/issues/26), but from serialization perspective.
[JSONAPI Resource …
=> Add meta and links for resource objects in serialization

src/middleware/json-api/res-errors.js
Relevant for responses such as 401 Unauthorized: 'Invalid email or token'
=> Support responses with text response data

src/middleware/json-api/_deserialize.js
Currently not blocking us because we are running on a fork but might hinder others.
This PR contains two changes:
This change is a tad older, so I hope I get the description right.
Currently, multi-worded attributes are automatically converted to camelCase by devour while relationships are kept in kebab-case in case they are defined like this for example:
```
this.jsonApi.define('category',{
name: '',
categoryType: '',
sort: '',
deleted: '',
createdAt: '',
updatedAt: '',
items:{
jsonApi: 'hasMany',
type: 'items'
},
'sub-categories':{
jsonApi: 'hasMany',
type: 'categories'
},
parent:{
jsonApi: 'hasOne',
type: 'category'
}
})
```
This issue can be solved by a middleware, which we did first. But a much simple change is the one included in this PR. More info on the issue can be found here: …
=> Fix handling of camel case notation in relationships and remove cache clearance

README.md, src/index.js, test/api/api-test.js, yarn.lock
Yes, we cannot update relationships which are not named the same as their type
Pretend we some models defined as such:
```js
jsonApi.define('tourist', {
name: '',
favourite_cities: {
jsonApi: 'hasMany',
type: 'city'
},
visited_cities: {
jsonApi: 'hasMany',
type: 'city'
}
})
jsonApi.define('city', { name: '' })
```
JSON:API allows us to modify the relationship between cities at a URL like `/tourists/1/relationships/visited_cities`—[see the docs here](http://jsonapi.org/format/#crud-updating-relationships).
However Devour assumes the relationship is named the same as the model:
```js
jsonApi.one('tourist', 1).relationships().all('visited_cities').patch(...)
// Error: API resource definition for model "visited_cities" not found. Available models: …
```
=> Modify relationships not named after their type

src/middleware/json-api/_deserialize.js, src/middleware/json-api/res-deserialize.js
Is this PR blocking your next action? I don't have a next action planned, but it blocks my project.
The deserialization cache is cleared after the whole deserialization process now instead of during deserialization.
A deserialized resource which might have been necessary in a later point of the deserialization process was removed out of the cache too early before the deserialization was finished. That led to a recursion which caused a `RangeError: Maximum call stack size exceeded`.
There's an issue for it:
https://github.com/twg/devour/issues/143
Adding this caching functionality was done by nicooga (https://github.com/nicooga) and @IDragonfire as part of issue https://github.com/twg/devour/issues/47.
=> Clear cache after deserialization and not during it.

src/middleware/json-api/res-errors.js
Some servers do not return [HTTP Status Text](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText) in the response. This result in the error message returned as 
': Invalid email or token' instead of 'Unauthorized: Invalid email or token'.
=> Do not print error response's status text when it is empty

src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
High, the current version is broken for everyone using kebab case notation in API responses (I think).
In a well-intended approach to improve readability, the deserialization of kebab-case attributes was broken in https://github.com/twg/devour/pull/165. This reverts that change and adds a test case.
A test case was added to prevent this in the future.
=> Fix deserialization of kebab case attributes by reverting attr renaming

package-lock.json, package.json
Update es6-promise to allow version 4
The version requirement for es6-promise did not allow using version 4 and up.
Update package.json to allow it and also update the lock file to the
lastest version.
Note: Running npm install also updated the version in package-lock.json,
which was out of date since version 2.0.24.
Fixes #188
=> Update es6-promise to allow version 4

test/api/api-test.js
High
I noticed some unit-test errors were not caught, and reported as success. I fixed the `catch` phrases to pass the error to `done()` so that the test will be regarded as failed.
N/A
Following this fix, two already failing tests needs to be fixed:
- Basic API calls: should accept a data payload on DELETE requests when provided as a third argument
- Basic API calls: should accept a meta and data payload on DELETE requests when provided as a third and fourth arguments:
=> Catch middleware exceptions

README.md, src/index.js, src/middleware/json-api/res-errors.js, test/api/configuration-test.js, test/helpers/mock-error.js
Low
I added a new functionality to be able to override the default error object returned by _devour-client_. I encountered a use case in which I needed to pass the _meta_ attribute from the server's error to the frontend (to display some extra data with the error). I noticed that the library builds an object with _title_ and _detail_ fields, and figured one might want to customize this.
Added unit-tests for this. See `test/api/configuration-test.js`
N/A
Updated `README.md` accordingly.
=> Add custom error builder

src/middleware/json-api/_serialize.js, test/api/api-test.js
Low
- Prevent undefined attributes from being serialized in the request
- Prevent the attributes object attribute from being serialized if empty
Added two unit-tests. See code.
https://github.com/twg/devour/issues/141
=> Do not serialize undefined attributes

package-lock.json, package.json
High
lodash dependency updated to >= 4.17.13 (4.17.15 specifically) to include patch for security advisory CVE-2019-10744.
- npm install
- npm test
Fixes #197
See lodash [patch for CVE-2019-10744](https://github.com/lodash/lodash/pull/4336)
=> Update lodash to 4.17.15

.gitignore, README.md, package.json, src/index.js, src/middleware/json-api/req-bearer.js, test/api/api-test.js
Low
Added in the following function:
- removeMiddleware in order to remove a middleware
Changes made to the following function:
- insertMiddleware to avoid the same middleware being added twice
Added in the following option for the constructor:
- bearer to set the Bearer Authorization token to be added in requests
Added the following middleware:
- add-bearer-token to set the Bearer Authorization token to requests
Unit tests have been written in order to verify the changes are working
=> Ability to easily set bearer token and removing middlewares

src/index.js
This fixes #203 .
The verification code makes it impossible to replace middleware (unless it has the exact same name).
The code checked the existance of the new middleware while it should be checking the existance of the previous middleware that will be replaced. I also added verification to check that we don't include the same code twice and fixed a grammar mistake.
The code below will fail without these changes; it won't fail with them.
```javascript
let errorMiddleware = {
name: 'only-status',
error: function (payload) {
return { status: payload.response.status }
}
}
jsonApi.replaceMiddleware('errors', errorMiddleware)
```
#203
=> Fix the verification for replacing middleware

src/middleware/json-api/_serialize.js, test/api/serialize-test.js
High
N/A
The meta object is now serialised for resource identifier objects in relationships.
The JSON:API specification says: A “resource identifier object” MAY also include a meta member, whose value is a meta object that contains non-standard meta-information. https://jsonapi.org/format/#document-resource-identifier-objects
This change allows to send meta information in relationship resource identifier objects as defined in the spec.
Unit tests were added.
https://jsonapi.org/format/#document-resource-identifier-objects
=> Serialize meta object into resource identifiers in relationship object

src/middleware/json-api/req-patch.js
Support for null data in relationship path as [documented here](https://jsonapi.org/format/#crud-updating-to-one-relationships)
=> support for null data in patch

src/index.js, test/api/api-test.js
Adds model to the request object returned by the `get` method to bring it line with other methods.
Also adds tests that confirm correct model is added to other methods.
https://github.com/twg/devour/issues/216
=> Add model to req object returned by get method

src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
Is this PR blocking your next action? - Kind of. We're using a patched version of devour for the moment.
It's valid JSON API to specify the ids of relationships without including the related resources under the 'included' key. Currently devour throws that information away. This PR keeps the ids of the related resources in the information returned by devour.
=> Keep ids of related resources that are not included in the response

src/middleware/json-api/_deserialize.js, test/api/deserialize-test.js
> Is this PR blocking your next action?
It is [blocking](https://github.com/twg/devour/pull/153#issuecomment-764777410) @unicrus.
Return type and id for non-included relations instead of just the id. The id alone is most probably not valid data and having the type and id is incredibly useful for fetching more information from an API.
This is, of course, a breaking change.
Mention people who would be interested in the changeset: @unicrus & @JaZo
Engineer(s) who wrote the old version: @graemetait
=> Keep type and id of non included relations

README.md
I added a note to the documentation about the requirement that the name of a middleware should be unique.
#206 introduced an issue in our implementation because we were replacing default middleware with a patched version using the same name. This resulted in a "The middleware errors already exists" error. But the requirement of a middleware having an unique name is nowhere to be found in the documentation.
=> Add note about uniqueness of middleware name

package-lock.json, package.json, src/index.js, src/middleware/json-api/_deserialize.js, src/middleware/json-api/_serialize.js, src/middleware/json-api/req-bearer.js, src/middleware/json-api/req-delete.js, src/middleware/json-api/req-get.js, src/middleware/json-api/req-patch.js, src/middleware/json-api/req-post.js, src/middleware/json-api/res-deserialize.js, src/middleware/json-api/res-errors.js, src/middleware/request.js, test/api/api-test.js, test/api/configuration-test.js, test/api/deserialize-test.js, test/api/serialize-test.js, test/helpers/mock-error.js, test/helpers/mock-response.js
My goal was to resolve [this dependabot alert](https://github.com/twg/devour/security/dependabot/package-lock.json/jsonpointer/open) and while doing so I upgraded the standard package to the latest version. Then I ran `npm run autofix` to format the code according to the latest standards (this makes the PR huge; my apologies) and fixed the mocha configuration since it got updated too and its default configuration settings changed over time.
TLDR: I dragged a few libraries into the modern age and this introduced many small code changes.
=> Upgrade jsonpointer, standard, and mocha

src/middleware/json-api/res-deserialize.js
In JSON:API the server responds with data structure called [a document](https://jsonapi.org/format/#document-structure). Devour-client will process it for us; it combines attributes and relationships etc. to obtain resources that are very easy to handle. However Devour will omit certain things in the deserialisation process. URLs in relationships for example. In most cases you don't need these, but if you do, there's really no way to obtain them and you're stuck.
This PR exposes the whole document as it was returned by the server to allow for a way around the deserialisation process.
=> Expose the whole document too

src/index.js, test/api/api-test.js
Fail fast if the caller tries to use `null` or `undefined` as the id.
Nothing good will come of it so you'd better know about it as soon as
possible.
Note that it's still possible to use the strings "null" or "undefined"
as the id which will construct the URLs you'd expect it to.
Automated tests have been added.
=> Throw an Error if id is nil

package-lock.json
Not really.
I simply ran `npm audit fix`
npm was warning me about these vulnerabilities:
```
fix available via `npm audit fix`
node_modules/istanbul-api/node_modules/async
nanoid  3.0.0 - 3.1.30
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix`
node_modules/nanoid
mocha  8.2.0 - 9.1.4
Depends on vulnerable versions of nanoid
node_modules/mocha
3 vulnerabilities (2 moderate, 1 high)
```
As far as I know they all are related to dev-dependencies; so they are not the most important things in the world. On the other hand, it's probably good practice to just upgrade them.
=> Upgrade mocha

package-lock.json, package.json, src/middleware/json-api/rails-params-serializer.js
When your app uses Axios 1.1.3 and you assign this axios instance to devour-client, it crashes on the `paramsSerializer` implementation. Axios 1.1.3 has a breaking change for this method.
- none
Before:
```js
config.paramsSerializer = params => doSomethingWithParams(params)
```
After:
```js
config.paramsSerializer = {
serialize: params => doSomethingWithParams(params)
}
```
- none
See the `paramsSerializer` documentation in https://github.com/axios/axios#request-config
- none
- none
- updated axios
Mention people who would be interested in the changeset:
Engineer(s) who wrote the old version: @tijn
=> Support Axios 1.1.3

README.md, src/index.js, test/api/api-test.js
N/A
Introduced a flag `disableErrorsForMissingResourceDefinitions` to effectively disable the error _'API resource definition for model "XWY" not found'_. Instead of throwing the error though, we are invoking the Logger's error method to let users know they should fix it.
Since invokers of the `modelFor` method expect a model, we are returning an empty model structure which has proved effective in our tests.
Just run the tests.
Updated the README file with instructions.
=> Resolves #250 Added a means to disable errors for missing resource definitions.

package-lock.json, package.json
- Remove the deprecated istanbul pacakage
- Install nyc
[Dependabot reported a vulnerability](https://github.com/devour-js/devour-client/security/dependabot/26) in babel-traverse. This in itself is not an issue for this project since we're not compiling code that's specifically crafted by an attacker with it. However, while looking at package-lock-json I found out that the reason for installing `babel-traverse` is `istanbul`. And that package has been deprecated. This PR replaces istanbul with nyc.
https://github.com/devour-js/devour-client/security/dependabot/26
https://www.npmjs.com/package/istanbul
nyc - it was recommended by the author of istanbul as its replacement. It also has a permissible ISC license, functionally equivalent to the simplified BSD and MIT licenses.
=> Resolve babel vulnerability
